In [8]:
import torch
from torch import nn

SM = nn.Softmax(-2)

input=torch.rand([2,2,4], dtype=torch.float32)
print(input)

output=SM(input)
print(output)
print(output.shape)

print(torch.sum(output))


SM2d = nn.Softmax2d()
output=SM2d(input)
print(output)
print(output.shape)

print(torch.sum(output))


tensor([[[5.2184e-01, 4.2307e-01, 1.1797e-02, 4.2784e-02],
         [6.1671e-01, 1.6867e-01, 2.0478e-01, 6.6302e-02]],

        [[4.7303e-01, 2.1696e-05, 7.3749e-01, 9.2057e-01],
         [7.2311e-01, 7.3123e-01, 5.0606e-01, 2.1894e-01]]])
tensor([[[0.4763, 0.5633, 0.4519, 0.4941],
         [0.5237, 0.4367, 0.5481, 0.5059]],

        [[0.4378, 0.3249, 0.5576, 0.6685],
         [0.5622, 0.6751, 0.4424, 0.3315]]])
torch.Size([2, 2, 4])
tensor(8.)
tensor([[[0.5122, 0.6042, 0.3261, 0.2936],
         [0.4734, 0.3630, 0.4252, 0.4619]],

        [[0.4878, 0.3958, 0.6739, 0.7064],
         [0.5266, 0.6370, 0.5748, 0.5381]]])
torch.Size([2, 2, 4])
tensor(8.)
