In [5]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel


tokenizer = GPT2Tokenizer.from_pretrained("/home/lihao/model/gpt2")
model = GPT2LMHeadModel.from_pretrained("/home/lihao/model/gpt2")
print(type(model))





<class 'transformers.models.gpt2.modeling_gpt2.GPT2LMHeadModel'>
tensor([[33331,   502,   257, 25607,  1621]])
<class 'torch.Tensor'>
final_outputs = tensor([[33331,   502,   257, 25607,  1621,   546,   703,   314,  1392,   656,
           262,   983,   290,   644,   314,  4499,   422,   340,    13,   314,
           892,   340,   338,  2495,  3608,    11,   290,   314,  1101,  1654,
           340,   338,   257,   922,  1621,    13,   198,   198,    40,   892,
           340,   338,   257,  2495,  3608,   983,   290,   314,  1101,  1654,
           340,   338,   257,   922,  1621,    13,   314,   892,   262,  1621,
           318,  2495,   922,    13,   198,   198,    40,   892,   262,  1621,
           318,  2495,   922,    13,   198,   198,    40,   892,   262,  1621,
           318,  2495,   922,    13,   198,   198,    40,   892,   262,  1621,
           318,  2495,   922,    13,   198,   198,    40,   892,   262,  1621]]), type(final_outputs) = <class 'torch.Tensor'>, final_outpu

In [1]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel


tokenizer = GPT2Tokenizer.from_pretrained("/home/lihao/model/gpt2")
model = GPT2LMHeadModel.from_pretrained("/home/lihao/model/gpt2")
print(type(model))

# 单请求
q = "tell me a fairy story"

ids = tokenizer.encode(q, return_tensors='pt')
print(ids)
print(type(ids))
final_outputs = model.generate(
    ids,
    do_sample=True,
    max_length=100,
    pad_token_id=model.config.eos_token_id,
    top_k=3,
    top_p=0.95,
)

print("final_outputs = {}, type(final_outputs) = {}, final_outputs.shape = {}".format(final_outputs, type(final_outputs), final_outputs.shape))

print(tokenizer.decode(final_outputs[0], skip_special_tokens=True))

/home/lihao/conda/miniconda3/envs/torch-dev/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


<class 'transformers.models.gpt2.modeling_gpt2.GPT2LMHeadModel'>
tensor([[33331,   502,   257, 25607,  1621]])
<class 'torch.Tensor'>
final_outputs = tensor([[33331,   502,   257, 25607,  1621,    11,   314,  1101,   407,  1016,
           284,  1560,   345,   257, 25607,  1621,    11,   475,   314,  1101,
          1016,   284,  1560,   345,   257,  1621,   326,   318,   845,    11,
           845,  1180,   422,   262, 25607, 12838,   326,   314,  1053,   587,
          1297,   526,   198,   198,   464,  1621,   318,  1912,   319,   257,
          1103,  1621,   326,   373,  1297,   416,   257,   582,  3706,  3977,
            13,   198,   198,     1,  1544,   373,   262,   582,   508,  1297,
           502,   262, 12838,   553,   339,  1139,    13,   366,    40,   373,
           262,   691,   530,   508,   714,  1560,   340,   526,   198,   198,
           464,  1621,  6140,   287,   257, 10016,  3240,   287,   262,  1578]]), type(final_outputs) = <class 'torch.Tensor'>, final_outpu

In [1]:
# 带 batch 的请求
from transformers import GPT2Tokenizer, GPT2LMHeadModel


tokenizer = GPT2Tokenizer.from_pretrained("/home/lihao/model/gpt2")
model = GPT2LMHeadModel.from_pretrained("/home/lihao/model/gpt2")
print(type(model))

# https://blog.csdn.net/shui123546yi/article/details/134823641

# 输入提示（批量）
prompts = [
    "Once upon a time in a magical forest",
    "In a distant galaxy, a young hero embarks on a quest",
    "A curious cat discovers a hidden treasure"
]

# ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
tokenizer.pad_token = tokenizer.eos_token

# 编码输入文本（批量）
# 注意，tokenizer.encode 会有问题，建议用 tokenizer 直接搞。返回的 ids 实际上是个 torch 的 tensor
ids = tokenizer(prompts, return_tensors='pt', padding=True, truncation=True, max_length=512)["input_ids"]


final_outputs = model.generate(
    ids,
    do_sample=True,
    max_length=100,
    pad_token_id=model.config.eos_token_id,
    top_k=3,
    top_p=0.95,
    num_return_sequences=3 # 每个输入（batch 中的某一条），返回几条数据，默认 1，
)

#print("final_outputs = {}, type(final_outputs) = {}, final_outputs.shape = {}".format(final_outputs, type(final_outputs), final_outputs.shape))
# tokenizer.batch_decode 比 tokenizer.decode(final_outputs[0], skip_special_tokens=True) 屌
output1 = tokenizer.batch_decode(final_outputs, skip_special_tokens=True)
# print("output1 = {}, type(output1) = {}, len(output1) = {}".format(output1, type(output1), len(output1)))
print("type(output1) = {}, len(output1) = {}".format(type(output1), len(output1)))

for result in output1:
    print("answers: {}".format(result))

# print(tokenizer.decode(final_outputs[0], skip_special_tokens=True))
# i = 0
# for idx in final_outputs:
#     print("{} {}".format(i, idx))
#     i += 1

/home/lihao/conda/miniconda3/envs/torch-dev/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


<class 'transformers.models.gpt2.modeling_gpt2.GPT2LMHeadModel'>


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


type(output1) = <class 'list'>, len(output1) = 9
answers: Once upon a time in a magical forestThe U.S. Supreme Court is set to hear arguments on whether the government can force a state to provide health care to its citizens without a warrant, a move that has been hailed by some as a step toward a more open and transparent system of health care.

The justices will hear arguments on Wednesday in the case, which is expected to be heard in Washington state on June 6.

The case, U.S
answers: Once upon a time in a magical forestThe U.S. Supreme Court on Thursday ruled that a Texas school district can ban a teacher from teaching a class about homosexuality, saying it's not in the public interest to ban it.

A district court in Houston ruled on Friday that a Texas law that requires teachers to teach about homosexuality is unconstitutional.

The case is the latest step in a long-running fight over the school district's ban of gay-straight alliance
answers: Once upon a time in a magical forestT

In [22]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel


tokenizer = GPT2Tokenizer.from_pretrained("/home/lihao/model/gpt2")

print(tokenizer)
print(type(tokenizer))

prompts = [
    "Once upon a time in a magical forest",
    "In a distant galaxy, a young hero embarks on a quest",
    "A curious cat discovers a hidden treasure"
]

print(tokenizer("Hello world")["input_ids"])
print(tokenizer(" Hello world")["input_ids"])
# padding=True,
tokenizer.pad_token = tokenizer.eos_token
data = tokenizer(prompts, return_tensors="pt", truncation=True, padding=True)["input_ids"]
print(data)
print(type(data))
print(type(data[0]))

GPT2Tokenizer(name_or_path='/home/lihao/model/gpt2', vocab_size=50257, model_max_length=1024, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
<class 'transformers.models.gpt2.tokenization_gpt2.GPT2Tokenizer'>
[15496, 995]
[18435, 995]
tensor([[ 7454,  2402,   257,   640,   287,   257, 10883,  8222, 50256, 50256,
         50256, 50256, 50256],
        [  818,   257, 12899, 16161,    11,   257,  1862,  4293,  4072,  5558,
           319,   257,  1235],
        [   32, 11040,  3797, 27472,   257,  7104, 14068, 50256, 50256, 50256,
         50256, 50256, 50256]])
<class 'torch.Tensor'>
<class 'torch.Tensor'>
